debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.yoon.projectadmin: debug
    org.springframework.web.servlet: debug    #request, response 만 log로 찍기 위해서
    org.hibernate.type.descriptor.sql.BasicBinder: trace    #query 를 바인딩 파라미터를 보기 위해서

server:
  port: 8081

spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true   #초기 데이터 생성 sql 실행 (data.sql)
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100       #벌크 사이즈 100개 한번에 select, 조회 성능 개선 -> n+1 쿼리 문제 해결
    open-in-view: false
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
